### ISSUE TITLE
Probably a user error, but possible a bug:  only first state group (tasks) works? ("reopening" issue 11)

### ISSUE THREAD

**Issue by engage-results** [thingnotok/obsidian-toggle-list#12]
I am having the same issue as the bug listed in issue 11.

Onle the first state group (tasks) works.

The original big poster said they resolve the problem. They were using the tool wrong. I'm likely using the tool wrong too, but have spent a few hours trying to work it out.

Can you help me use the tool correctly? (more likely) Or treat this as an actual bug? (less likely)

**Comment by thingnotok** [comment]
Hi, no worry, we can resolve this, whether it's a bug or anything.
can you show me the screenshot of your setup? including the related hotkeys. 
if possible please also show the data.json file under the plugin folder `path_of_vault/.obsidian/obsidian-toggle-list/data.json`. That can help me reproduce the bug. 😃

**Comment by engage-results** [comment]
Thank you for the lightning fast response.

I worked out my user error. Doubt it's a bug, but it might be helpful to highlight issue in the documentation (I'd even like to see it in the "help text" that's already featured on the settings page, if you think that would be helpful.)

The user has to include the "start state" somewhere in the list when configuring the settings. If you said this in the docs I missed it. Which is entirely possible. 

In hindsight, now that I worked it out, it seems obvious. Your plugin has to match the current line to a state in the list to advance to the next "toggle".

This is what I've worked out.

**Task**
So in the default set up you have a blank line at the end of the list of toggle values for State 0.  That means I can start with a normal line and toggle through all the task options (the normal line matches the blank entry).

**Task Priority**
The default for State 1 (Task priority in the default) includes a normal task with no priority and also priorities p1, p2 and p3 on separate lines, but there is no blank line at the end. Which means you can't start with a normal line.  You either have to start with an unprioritised task, or a task is already prioritised.  If you try to toggle State 1 on a normal line nothing happens.

**Call Out**
The default for State 2 is similar to State 1. There is no blank line to match a  normal list so nothing happens if you togglelist Call Out (State 2)  on a "normal line".  To get the togglelist call out behaviour with the default config you already have to have a call out list (ie start with "- ? playground".

Finally, I think this is the behavior I want. It allows me the most configuration options.  But I have to  know that the blank line at the end of the list is important for activating the toggle behaviour on a "normal" line.

The difficult here is that the blank line on the default State 0 and the lack of blank line in the other states is not obvious just by looking.

If you make a change, I would consider putting the blank line at the end of each default settings list.  I think this  could be less confusing behaviour.

As I said this gives the most configurability. Another feature that I could imagine as an option (but would like the choice to enable or not) is to behave like the core "Toggle Checkbox" command.   The first time you Toggle "core" Checkbox on a normal link it adds the markdown for an (unchecked) checkbox. After that it only toggles between checked and unchecked. 

Also it will turn a bullet into an (unchecked) checkbox and then from then on it toggles between checked and unchecked.

This also means with the list  Call Out plugin  you can turn a list call out to a Task + Call Out if you already have a list call out. 

I'd be happy to see this behaviour in your plugin as an optional feature. But I'm also very happy if you choose not to do that.

First, I know you are aware of this. I tried to explain in details for the next person that might read this.

And second, apologies if this is already well documented and i missed this.

I am going to love this plugin.  So thank you.

**Comment by thingnotok** [comment]
Thanks a lot for your detailed explanation!  I didn't emphasis these stuffs in the docs. 

After reading your usecase, I do also think adding blank line in each group (as default) is a good idea. I design the default settings to show various purposes, but your usecase show the power of integrating groups together! If you don't mind, may I use some of your explanation in the new version of documents? 

I'm also thinking that maybe a state diagram can be a perfect tool to show all these setups.
(I use arrow color to identify commands)
__your version__
![image](https://user-images.githubusercontent.com/29173832/214589395-f7a14047-5a5a-4874-b6c8-8528fae05ae6.png)

__original setup__
![image](https://user-images.githubusercontent.com/29173832/214590261-09dbf186-0ff2-4bea-a83d-3bff310961bd.png)

- [x] Update the documents 
    - [x] to show usecase of integrating groups, using state diagram
    - [x] to emphasis the triggering condition (hotkey + line matching)
- [x] decide whether to add blank line in each group as default

**Comment by engage-results** [comment]
Sure, I'm happy for you use any part of that explanation that you find helpful. 

The state diagrams are also really helpful to me, but I  am not sure if I would have figured it out from the state diagrams alone :)

Now that I grok it, i can see even more possibilities looking at your state diagrams.  Thanks!

Thanks for being so quick on this.

**Comment by thingnotok** [comment]
Finished in [1.0.7](https://github.com/thingnotok/obsidian-toggle-list/releases/tag/1.0.7)
